### ISSUE TITLE
Use JSON Schema generated by Drafter

### ISSUE THREAD

**Issue by IvanGoncharov** [kminami/apib2swagger#10]
@kminami It's look like drafter now generate JSON Schema on it's own:
https://github.com/apiaryio/drafter/pull/191
It would be great to use it.

**Comment by kminami** [comment]
Good news, thanks!
I will try to use it.

**Comment by kminami** [comment]
Certainly, drafter@2.1.0 generates schema fields using MSON (Attributes section).
If a schema field exists, current apib2swagger uses it as-is instead of self-converting from MSON, so our to do is just only updating drafter to 2.1.0.
However, I noticed that current drafter is something wrong, e.g.
```
// 09. Advanced Attributes.md
+ Response 200 (application/json)
    + Attributes (Coupon)
```
generates
```
{¥n  \"$schema\": \"http://json-schema.org/draft-04/schema#\",\n  \"type\": \"object\",\n  \"properties\": {\n    \"type\": \"object\"\n  }\n}
```
I expects a result that embeds or references the Coupon schema.

**Comment by IvanGoncharov** [comment]
> I expects a result that embeds or references the Coupon schema.

Because JSON Schema is in form of string so it can't reference other schemas in the same document.
I have same problem with RAML converter :disappointed:

**Comment by IvanGoncharov** [comment]
@kminami They fixing `"properties\": {\n    \"type\": \"object\"\n  }\n` bug, see https://github.com/apiaryio/drafter/pull/201

**Comment by jykae** [comment]
@kminami Are you working on this? We are looking for API Blueprint <-> Swagger conversion. If this is not developed, do you now if there are any other options to use?

**Comment by kminami** [comment]
@jykae This project is active. Drafter's schema output doesn't look good to me yet (it fails my tests).
If you have problems, please let me know. Contributions are also welcome!

**Comment by kminami** [comment]
"drafter.js": "^2.0.0" now installs drafter.js 2.4.3, then JSON Schema generated by drafter will be used automatically.
(I had thought ^2.0.0 means 2.0.x, but...)
