### ISSUE TITLE
HTTP message-header Accept not converted to consumes

### ISSUE THREAD

**Issue by jkeffer** [kminami/apib2swagger#11]
This Blueprint section

+ Request

    + Headers

            Accept: text/plain

should create Swagger output that contains:

"consumes": ["text/plain"]

Without "consumes", the request header contains Accept: application/json and plain text responses fail.

It doesn't matter what is specified for Accept in the Blueprint input.

**Comment by kminami** [comment]
Did you talk about "produces"?
I think "consumes" relates to Content-Type header of http request.

"produces" can be converted from Accept header in Request section (you described) and Content-Type header in Response section (my preference).
Is it write?

p.s.
Describing the tool you use is also helpful for me.

**Comment by jkeffer** [comment]
I'm executing the APIs in Swagger and I have the debug console open in my browser to check the request and response headers. I'm using swagger-ui.js.

It doesn't matter what I put in the Headers section in the Blueprint file. I don't get either "produces" or "consumes" in the Swagger output.

If I manually add "produces":["text/plain"],  Swagger adds Accept: text/plain when I execute the API:


curl -X GET --header 'Accept: text/plain'


These are the headers:

Request Headers
{
  "Accept": "text/plain"
}

Response Headers
{
  "content-type": "text/plain",
  "cache-control": "no-cache=\"set-cookie\""
}

Earlier today I used "consumes" and it worked, but now only "produces" works.

In any case, the conversion from Blueprint to Swagger doesn't add either "produces" or "consumes" and it defaults to "Accept": "application/json".

Thanks.

Julia Keffer, Senior Staff Technical Writer, Wind River
direct 613.963.1396 cell 613.867.3156 Skype: julia_keffer

________________________________

**Comment by kminami** [comment]
Implemented. Cloud you please try it with master?

**Comment by jkeffer** [comment]
It works for me.

Thanks.

Julia Keffer, Senior Staff Technical Writer, Wind River
direct 613.963.1396 cell 613.867.3156 Skype: julia_keffer

________________________________

**Comment by kminami** [comment]
Thank you! 
Published to npm as v0.6.0.
