### ISSUE TITLE
Allow input file or output file to be stdin/stdout

### ISSUE THREAD

**Issue by frostyfrog** [kminami/apib2swagger#16]
There are a few instances where it would be nice to use pipes instead of actual files when converting apib files to a swagger json file. An example of such usage might be:

    cat header.apib admin.apib database.apib users.apib | apib2swagger -i - -o - | curl -F 'f:1=<-' https://example.com/upload

**Comment by kminami** [comment]
Implemented at merge request #17 and released as v0.7.0.
Thanks.
