### ISSUE TITLE
Some outputs are not valid against swagger 2.0 json schema

### ISSUE THREAD

**Issue by KarelJakubec** [kminami/apib2swagger#18]
Hi @kminami,
at first let me thank you for this wonderful tool. I use it currently quite extensively to convert blueprints. We've integrated it into our system, which stores just swagger and it checks validity of each swagger file before storing. I've discovered that there are some outputs which are not valid against swagger 2.0 schema.

For instance:
- Body parameters in swagger dost not support "type" and "default" properties, all must be stored under "schema" property as json schema.
- "required" property in json schema must always be non-empty array or must not be present

I am enclosing a pull request (which however depends on my previous pull request) that should solve the issues I've found. There is also a test which now validates all inputs against swagger json schema and ome blueprints for testing purposes which caused the troubles.

I still know about one valid blueprint which is converted to non-valid swagger, but it's bit a more complex issue than these two, so I will push it later once it's solved properly.

Best regards,
Karel

**Comment by KarelJakubec** [comment]
Aha, so Github is smarter than I thought and it merged this pull request with my previous pull request #17  for issue #16 . So if the code satisfy your demands merge it together please.

**Comment by kminami** [comment]
#17 was merged. Thanks!
I'm very happy to hear that this tool helps you.
