### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by SamuelMarks** [kminami/apib2swagger#2]
I like the look of your project, so I `curl`d down the an [API blueprint example](https://raw.githubusercontent.com/apiaryio/api-blueprint/master/examples/Real%20World%20API.md), and installed (npm 2.11.3, node v0.12.7) the latest apib2swagger.

Unfortunately here's the output from running `apib2swagger -i RealWorldAPI.md -o foo.json`:
```
/home/sm/n/lib/node_modules/apib2swagger/index.js:11
        'title': apib.name,
                     ^
TypeError: Cannot read property 'name' of undefined
    at module.exports.convertParsed (/home/sm/n/lib/node_modules/apib2swagger/index.js:11:22)
    at /home/sm/n/lib/node_modules/apib2swagger/index.js:289:23
sm@Afz:/tmp$ mv Real%20World%20API.md RealWorldAPI.md
sm@Afz:/tmp$ apib2swagger -i RealWorldAPI.md
/home/sm/n/lib/node_modules/apib2swagger/index.js:11
        'title': apib.name,
                     ^
TypeError: Cannot read property 'name' of undefined
    at module.exports.convertParsed (/home/sm/n/lib/node_modules/apib2swagger/index.js:11:22)
    at /home/sm/n/lib/node_modules/apib2swagger/index.js:289:23
sm@Afz:/tmp$ apib2swagger -i RealWorldAPI.md -o foo.json
/home/sm/n/lib/node_modules/apib2swagger/index.js:11
        'title': apib.name,
                     ^
TypeError: Cannot read property 'name' of undefined
    at module.exports.convertParsed (/home/sm/n/lib/node_modules/apib2swagger/index.js:11:22)
    at /home/sm/n/lib/node_modules/apib2swagger/index.js:289:23
```

How do I resolve this issue?

Thanks for all suggestions,

Samuel

PS: Your `input` directory is empty so I can't see what you expect => https://github.com/kminami/apib2swagger/tree/master/test/input

EDIT: Debugging around a little and I found the problem. The `convertParsed` function's `apib` argument isn't being populated (it's `undefined`).

**Comment by kminami** [comment]
Thanks you for trying!
I found the reason that protagonist (dependency of this project) was updated to 1.0.0 and lost the compatibility.
Could you retry with apib2swagger v0.3.1 ?

**Comment by SamuelMarks** [comment]
No worries, actually turns out what I was using was v0.3.1. What version of protagonist should I roll back to?

**Comment by SamuelMarks** [comment]
I'll close the issue, now you know the issue is that your package needs to be changed to work with the latest protagonist
