### ISSUE TITLE
<!-- include(file.apib) --> files do not get imported 

### ISSUE THREAD

**Issue by graph1994** [kminami/apib2swagger#20]
As a user, if I have a base file with an `<!-- include(file.apib) -->` tag pointing to another file, I would expect that it would be included correctly when running `apib2swagger -i api-guide.apib -o api-guide-swagger.json`

**Comment by kminami** [comment]
Same as #12 , but will try to support it.

**Comment by kminami** [comment]
Released as 0.8.0.
