### ISSUE TITLE
OpenAPI 3.0 support?

### ISSUE THREAD

**Issue by marks** [kminami/apib2swagger#28]
Just curious - any plans to support OpenAPI 3.0?

**Comment by kminami** [comment]
Yes, I’m interested in it.
However, there is no progress now.

**Comment by MikeRalphson** [comment]
@marks are there any particular features of OpenAPI 3.0 where it would be useful to capture some more information in the conversion from API Blueprint? 

There is a '[standard](https://github.com/Mermade/swaggerplusplus/blob/master/README.md#swaggerplusplus)' for OpenAPI 2.0 extensions to hold some of this data (such as `x-servers`) which can then be picked up by a compliant converter, such as [swagger2openapi](https://github.com/mermade/swagger2openapi).

**Comment by funkeyfreak** [comment]
Greetings @kminami - I have an engineering team who would like to take this on. Can we take this on?

**Comment by kminami** [comment]
@funkeyfreak Of course, contributions are always welcome!

**Comment by funkeyfreak** [comment]
Thank you @kminami  - we should have a PR created shortly with the modifications to handle OpenAPI 3.0 🎉

**Comment by funkeyfreak** [comment]
@kminami - can you review PR #53 ? My teammate has completed the code necessary to support OpenAPI 3 🎉 🎉 🎉

**Comment by kminami** [comment]
I have just released it as v1.13.0.
Thank you!
