### ISSUE TITLE
Enums are not referenced

### ISSUE THREAD

**Issue by candus** [kminami/apib2swagger#33]
Dear developers,

here is my problem: if I use an enum as a data structure, it is not converted as a reference to the structure, but the enum is used directly.

Here is my input apiary:

FORMAT: 1A

# INT-1\_Plan\_v1\_dev

This API is a HTTP-1.1 REST service that provides plans

**Changelog**

| Date of change    | Description       |
| ----------------- | ----------------- |
| 03.08.2018        | Document creation |

# Group People

### Get Plans of People [GET]

* Paginated &#10006;

* Sortable &#10006;

* Signable &#10006;

#### Error Codes

Possible error codes for this resource.

| HTTP Status Code  | Error Code        | Purpose   |
| ----------------- | ----------------- | --------- |
| 400               | VALIDATION\_ERROR | Validation error. |
| 400               | FIELD\_MISSING    | A required field is missing. |

+ Parameters
    + dateFrom: `2018-08-01` (string, optional) - Date from.
    + dateTo: `2018-08-30` (string, optional) - Date to.

+ Request

    + Headers

            some-key: <here comes some key>
            auth: <here comes some token>

+ Response 200 (application/json)

    + Attributes (object)
        + segments (array[SEGMENT_ENUM], required, fixed-type) - List of found segments
        + plans (array, required, fixed-type) - List of plans
            + (object)
                + state: COMPLETED (string, required) - State code
                + stateCounters (array, required, fixed-type) - List of states of plans by segment
                    + (object)
                        + segment (SEGMENT_ENUM, required) - segment code
                        + count: 5 (number, required) - number of plans

# Data Structures

## `SEGMENT_ENUM` (enum)

+ LOW
+ MIDDLE
+ HIGH

And here is the result swagger:

swagger: '2.0'
info:
  title: INT-1_Plan_v1_dev
  version: ''
  description: |-
    This API is a HTTP-1.1 REST service that provides plans

    **Changelog**

    | Date of change    | Description       |
    | ----------------- | ----------------- |
    | 03.08.2018        | Document creation |
paths:
  /myapp/people/plans:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          examples:
            application/json:
              segments:
                - LOW
              plans:
                - state: COMPLETED
                  stateCounters:
                    - segment: LOW
                      count: 5
          schema:
            type: object
            properties:
              segments:
                type: array
                items:
                  type: string
                  enum:
                    - LOW
                    - MIDDLE
                    - HIGH
                description: List of found segments
              plans:
                type: array
                items:
                  type: object
                  properties:
                    state:
                      type: string
                      description: State code
                    stateCounters:
                      type: array
                      items:
                        type: object
                        properties:
                          segment:
                            type: string
                            enum:
                              - LOW
                              - MIDDLE
                              - HIGH
                            description: segment code
                          count:
                            type: number
                            description: number of plans
                        required:
                          - segment
                          - count
                      description: List of states of plans by segment
                  required:
                    - state
                    - stateCounters
                description: List of plans
            required:
              - segments
              - plans
      summary: Get Plans of People
      description: |-
        * Paginated &#10006;

        * Sortable &#10006;

        * Signable &#10006;

        #### Error Codes

        Possible error codes for this resource.

        | HTTP Status Code  | Error Code        | Purpose   |
        | ----------------- | ----------------- | --------- |
        | 400               | VALIDATION\_ERROR | Validation error. |
        | 400               | FIELD\_MISSING    | A required field is missing. |
      tags:
        - People
      parameters:
        - name: dateFrom
          in: query
          description: Date from.
          required: false
          x-example: '2018-08-01'
          type: string
        - name: dateTo
          in: query
          description: Date to.
          required: false
          x-example: '2018-08-30'
          type: string
      produces:
        - application/json
definitions:
  Collection of Plans of People: {}
  SEGMENT_ENUM:
    allOf:
      - $ref: '#/definitions/enum'
      - type: object
        properties: {}

SEGMENT_ENUM is not used above. Instead, its value were pasted directly to the place where it is used. In addition, SEGMENT_ENUM has a reference to "#/definitions/enum" which does not exist. Is there a different way how I can share my enums with a few REST services?

**Comment by kminami** [comment]
The latter problem was fixed at v1.2.0. Thanks!

**Comment by kminami** [comment]
The former problem is also fixed at v1.4.0 with --prefer-reference option.

**Comment by candus** [comment]
Thank you
