### ISSUE TITLE
Objects are not referenced

### ISSUE THREAD

**Issue by candus** [kminami/apib2swagger#36]
The attributes of objects used in responses (and everywhere in the interface description) are directly copy-pasted without using reference to the object. References are used only when pointing from an object definition to another definition.

### Desired solution
references should be used in Swagger in all places, where they were used in Api Blueprint

### Example Api Blueprint
...
+ Response 200 (application/json)
    + Attributes (object)
        + segment (SEGMENT) - One segment.
        + segmentsArray (array[SEGMENT], fixed-type) - Array of segments.
...

--- Data Structures

--- PLAN (object)
+ segment (SEGMENT) - One segment.
+ segmentsArray (array[SEGMENT], fixed-type) - Array of segments.

--- SEGMENT (object)
+ attr1
+ attr2
+ attr3

### Example generated Swagger

    get:
      responses:
        '200':
          description: OK
          headers: {}
          examples:
            application/json:
              segment:
                attr1: ''
                attr2: ''
                attr3: ''
              segmentsArray:
                - attr1: ''
                  attr2: ''
                  attr3: ''
          schema:
            type: object
            properties:
              segment:
                type: object
                properties:
                  attr1:
                    type: string
                  attr2:
                    type: string
                  attr3:
                    type: string
                description: One segment.
              segmentsArray:
                type: array
                items:
                  type: object
                  properties:
                    attr1:
                      type: string
                    attr2:
                      type: string
                    attr3:
                      type: string
                description: Array of segments.
      summary: Get Plans of People
      description: xyz
      tags:
        - People
      parameters:
        - name: dateFrom
          in: query
          description: Date from.
          required: false
          x-example: '2018-08-01'
          type: string
        - name: dateTo
          in: query
          description: Date to.
          required: false
          x-example: '2018-08-30'
          type: string
      produces:
        - application/json
definitions:
  Collection of Plans of People: {}
  PLAN:
    type: object
    properties:
      segment:
        type: SEGMENT
      segmentsArray:
        type: array
        items:
          $ref: '#/definitions/SEGMENT'
  SEGMENT:
    type: object
    properties:
      attr1:
        type: string
      attr2:
        type: string
      attr3:
        type: string

**Comment by kminami** [comment]
Same as #33.
OK, I will add a flag to change behavior.

**Comment by candus** [comment]
Thank you.

**Comment by kminami** [comment]
Added --prefer-reference option at v1.4.0.
Thanks!
