### ISSUE TITLE
Security authorization header not generated?

### ISSUE THREAD

**Issue by coboshm** [kminami/apib2swagger#38]
Hi! 

I'm trying to export to swagger some http request methods with Header Authorization and the swagger security section is not generated. 

```
## Whatever [GET /whatever{?limit}]

+ Parameters

    + limit (number, optional) - The maximum number of results to return.
        + Default: `10`

+ Request basic (application/json)

    + Headers
    
            Authorization: Basic 12345
```

But in the generated swagger.json there is nothing about the Header in the request neither about the security section. Do you have any idea?

Thanks

**Comment by kminami** [comment]
OK, I will add this feature.
Thanks!

**Comment by kminami** [comment]
Released as v1.6.0.
Thnaks!

**Comment by dhontecillas** [comment]
thank you very much! this is really useful.

**Comment by coboshm** [comment]
Thank you!!!
