### ISSUE TITLE
Does not work with the latest node version v4.1.1

### ISSUE THREAD

**Issue by tbostelmann** [kminami/apib2swagger#5]
Tested with v4.1.1 on both OS X and Linux (Ubuntu 14.04) and it failed.

Was able to get it to compile with v0.12.

(was not able to attach output so I'm copy/pasting it in issue - apologies).

$ npm install -g apib2swagger
-
> protagonist@0.20.1 install /home/tbostelmann/.nvm/versions/node/v4.1.1/lib/node_modules/apib2swagger/node_modules/protagonist
> node-gyp rebuild

make: Entering directory `/home/tbostelmann/.nvm/versions/node/v4.1.1/lib/node_modules/apib2swagger/node_modules/protagonist/build'
  CXX(target) Release/obj.target/libmarkdownparser/drafter/ext/snowcrash/ext/markdown-parser/src/ByteBuffer.o
  CXX(target) Release/obj.target/libmarkdownparser/drafter/ext/snowcrash/ext/markdown-parser/src/MarkdownNode.o
  CXX(target) Release/obj.target/libmarkdownparser/drafter/ext/snowcrash/ext/markdown-parser/src/MarkdownParser.o
  AR(target) Release/obj.target/drafter/ext/snowcrash/markdownparser.a
  COPY Release/markdownparser.a
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/HTTP.o
In file included from ../drafter/ext/snowcrash/src/Blueprint.h:17:0,
                 from ../drafter/ext/snowcrash/src/HTTP.h:13,
                 from ../drafter/ext/snowcrash/src/HTTP.cc:9:
../drafter/ext/snowcrash/src/MSON.h:371:37: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
             std::auto_ptr<Elements> m_elements;
                                     ^
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/MSON.o
In file included from ../drafter/ext/snowcrash/src/MSON.cc:9:0:
../drafter/ext/snowcrash/src/MSON.h:371:37: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
             std::auto_ptr<Elements> m_elements;
                                     ^
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/MSONOneOfParser.o
In file included from ../drafter/ext/snowcrash/src/Blueprint.h:17:0,
                 from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:12,
                 from ../drafter/ext/snowcrash/src/ModelTable.h:21,
                 from ../drafter/ext/snowcrash/src/SectionParserData.h:12,
                 from ../drafter/ext/snowcrash/src/SectionProcessor.h:12,
                 from ../drafter/ext/snowcrash/src/SignatureSectionProcessor.h:12,
                 from ../drafter/ext/snowcrash/src/SectionParser.h:13,
                 from ../drafter/ext/snowcrash/src/MSONMixinParser.h:12,
                 from ../drafter/ext/snowcrash/src/MSONOneOfParser.h:12,
                 from ../drafter/ext/snowcrash/src/MSONOneOfParser.cc:9:
../drafter/ext/snowcrash/src/MSON.h:371:37: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
             std::auto_ptr<Elements> m_elements;
                                     ^
In file included from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:13:0,
                 from ../drafter/ext/snowcrash/src/ModelTable.h:21,
                 from ../drafter/ext/snowcrash/src/SectionParserData.h:12,
                 from ../drafter/ext/snowcrash/src/SectionProcessor.h:12,
                 from ../drafter/ext/snowcrash/src/SignatureSectionProcessor.h:12,
                 from ../drafter/ext/snowcrash/src/SectionParser.h:13,
                 from ../drafter/ext/snowcrash/src/MSONMixinParser.h:12,
                 from ../drafter/ext/snowcrash/src/MSONOneOfParser.h:12,
                 from ../drafter/ext/snowcrash/src/MSONOneOfParser.cc:9:
../drafter/ext/snowcrash/src/MSONSourcemap.h:177:51: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
         std::auto_ptr<SourceMap<mson::Elements> > m_elements;
                                                   ^
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/MSONSourcemap.o
In file included from ../drafter/ext/snowcrash/src/Blueprint.h:17:0,
                 from ../drafter/ext/snowcrash/src/MSONSourcemap.h:12,
                 from ../drafter/ext/snowcrash/src/MSONSourcemap.cc:9:
../drafter/ext/snowcrash/src/MSON.h:371:37: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
             std::auto_ptr<Elements> m_elements;
                                     ^
In file included from ../drafter/ext/snowcrash/src/MSONSourcemap.cc:9:0:
../drafter/ext/snowcrash/src/MSONSourcemap.h:177:51: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
         std::auto_ptr<SourceMap<mson::Elements> > m_elements;
                                                   ^
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/MSONTypeSectionParser.o
In file included from ../drafter/ext/snowcrash/src/Blueprint.h:17:0,
                 from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:12,
                 from ../drafter/ext/snowcrash/src/ModelTable.h:21,
                 from ../drafter/ext/snowcrash/src/SectionParserData.h:12,
                 from ../drafter/ext/snowcrash/src/SectionProcessor.h:12,
                 from ../drafter/ext/snowcrash/src/SignatureSectionProcessor.h:12,
                 from ../drafter/ext/snowcrash/src/SectionParser.h:13,
                 from ../drafter/ext/snowcrash/src/MSONMixinParser.h:12,
                 from ../drafter/ext/snowcrash/src/MSONOneOfParser.h:12,
                 from ../drafter/ext/snowcrash/src/MSONTypeSectionParser.cc:9:
../drafter/ext/snowcrash/src/MSON.h:371:37: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
             std::auto_ptr<Elements> m_elements;
                                     ^
In file included from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:13:0,
                 from ../drafter/ext/snowcrash/src/ModelTable.h:21,
                 from ../drafter/ext/snowcrash/src/SectionParserData.h:12,
                 from ../drafter/ext/snowcrash/src/SectionProcessor.h:12,
                 from ../drafter/ext/snowcrash/src/SignatureSectionProcessor.h:12,
                 from ../drafter/ext/snowcrash/src/SectionParser.h:13,
                 from ../drafter/ext/snowcrash/src/MSONMixinParser.h:12,
                 from ../drafter/ext/snowcrash/src/MSONOneOfParser.h:12,
                 from ../drafter/ext/snowcrash/src/MSONTypeSectionParser.cc:9:
../drafter/ext/snowcrash/src/MSONSourcemap.h:177:51: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
         std::auto_ptr<SourceMap<mson::Elements> > m_elements;
                                                   ^
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/MSONValueMemberParser.o
In file included from ../drafter/ext/snowcrash/src/Blueprint.h:17:0,
                 from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:12,
                 from ../drafter/ext/snowcrash/src/ModelTable.h:21,
                 from ../drafter/ext/snowcrash/src/SectionParserData.h:12,
                 from ../drafter/ext/snowcrash/src/SectionProcessor.h:12,
                 from ../drafter/ext/snowcrash/src/SignatureSectionProcessor.h:12,
                 from ../drafter/ext/snowcrash/src/SectionParser.h:13,
                 from ../drafter/ext/snowcrash/src/MSONMixinParser.h:12,
                 from ../drafter/ext/snowcrash/src/MSONOneOfParser.h:12,
                 from ../drafter/ext/snowcrash/src/MSONValueMemberParser.cc:9:
../drafter/ext/snowcrash/src/MSON.h:371:37: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
             std::auto_ptr<Elements> m_elements;
                                     ^
In file included from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:13:0,
                 from ../drafter/ext/snowcrash/src/ModelTable.h:21,
                 from ../drafter/ext/snowcrash/src/SectionParserData.h:12,
                 from ../drafter/ext/snowcrash/src/SectionProcessor.h:12,
                 from ../drafter/ext/snowcrash/src/SignatureSectionProcessor.h:12,
                 from ../drafter/ext/snowcrash/src/SectionParser.h:13,
                 from ../drafter/ext/snowcrash/src/MSONMixinParser.h:12,
                 from ../drafter/ext/snowcrash/src/MSONOneOfParser.h:12,
                 from ../drafter/ext/snowcrash/src/MSONValueMemberParser.cc:9:
../drafter/ext/snowcrash/src/MSONSourcemap.h:177:51: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
         std::auto_ptr<SourceMap<mson::Elements> > m_elements;
                                                   ^
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/Blueprint.o
In file included from ../drafter/ext/snowcrash/src/Blueprint.h:17:0,
                 from ../drafter/ext/snowcrash/src/Blueprint.cc:9:
../drafter/ext/snowcrash/src/MSON.h:371:37: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
             std::auto_ptr<Elements> m_elements;
                                     ^
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/BlueprintSourcemap.o
In file included from ../drafter/ext/snowcrash/src/Blueprint.h:17:0,
                 from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:12,
                 from ../drafter/ext/snowcrash/src/BlueprintSourcemap.cc:9:
../drafter/ext/snowcrash/src/MSON.h:371:37: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
             std::auto_ptr<Elements> m_elements;
                                     ^
In file included from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:13:0,
                 from ../drafter/ext/snowcrash/src/BlueprintSourcemap.cc:9:
../drafter/ext/snowcrash/src/MSONSourcemap.h:177:51: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
         std::auto_ptr<SourceMap<mson::Elements> > m_elements;
                                                   ^
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/Section.o
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/Signature.o
In file included from ../drafter/ext/snowcrash/src/Blueprint.h:17:0,
                 from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:12,
                 from ../drafter/ext/snowcrash/src/ModelTable.h:21,
                 from ../drafter/ext/snowcrash/src/SectionParserData.h:12,
                 from ../drafter/ext/snowcrash/src/SectionProcessor.h:12,
                 from ../drafter/ext/snowcrash/src/SignatureSectionProcessor.h:12,
                 from ../drafter/ext/snowcrash/src/SectionParser.h:13,
                 from ../drafter/ext/snowcrash/src/Signature.cc:10:
../drafter/ext/snowcrash/src/MSON.h:371:37: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
             std::auto_ptr<Elements> m_elements;
                                     ^
In file included from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:13:0,
                 from ../drafter/ext/snowcrash/src/ModelTable.h:21,
                 from ../drafter/ext/snowcrash/src/SectionParserData.h:12,
                 from ../drafter/ext/snowcrash/src/SectionProcessor.h:12,
                 from ../drafter/ext/snowcrash/src/SignatureSectionProcessor.h:12,
                 from ../drafter/ext/snowcrash/src/SectionParser.h:13,
                 from ../drafter/ext/snowcrash/src/Signature.cc:10:
../drafter/ext/snowcrash/src/MSONSourcemap.h:177:51: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
         std::auto_ptr<SourceMap<mson::Elements> > m_elements;
                                                   ^
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/snowcrash.o
In file included from ../drafter/ext/snowcrash/src/Blueprint.h:17:0,
                 from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:12,
                 from ../drafter/ext/snowcrash/src/snowcrash.h:12,
                 from ../drafter/ext/snowcrash/src/snowcrash.cc:9:
../drafter/ext/snowcrash/src/MSON.h:371:37: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
             std::auto_ptr<Elements> m_elements;
                                     ^
In file included from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:13:0,
                 from ../drafter/ext/snowcrash/src/snowcrash.h:12,
                 from ../drafter/ext/snowcrash/src/snowcrash.cc:9:
../drafter/ext/snowcrash/src/MSONSourcemap.h:177:51: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
         std::auto_ptr<SourceMap<mson::Elements> > m_elements;
                                                   ^
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/UriTemplateParser.o
In file included from ../drafter/ext/snowcrash/src/Blueprint.h:17:0,
                 from ../drafter/ext/snowcrash/src/UriTemplateParser.h:12,
                 from ../drafter/ext/snowcrash/src/UriTemplateParser.cc:9:
../drafter/ext/snowcrash/src/MSON.h:371:37: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
             std::auto_ptr<Elements> m_elements;
                                     ^
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/HeadersParser.o
In file included from ../drafter/ext/snowcrash/src/Blueprint.h:17:0,
                 from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:12,
                 from ../drafter/ext/snowcrash/src/ModelTable.h:21,
                 from ../drafter/ext/snowcrash/src/SectionParserData.h:12,
                 from ../drafter/ext/snowcrash/src/SectionProcessor.h:12,
                 from ../drafter/ext/snowcrash/src/SignatureSectionProcessor.h:12,
                 from ../drafter/ext/snowcrash/src/SectionParser.h:13,
                 from ../drafter/ext/snowcrash/src/HeadersParser.h:12,
                 from ../drafter/ext/snowcrash/src/HeadersParser.cc:1:
../drafter/ext/snowcrash/src/MSON.h:371:37: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
             std::auto_ptr<Elements> m_elements;
                                     ^
In file included from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:13:0,
                 from ../drafter/ext/snowcrash/src/ModelTable.h:21,
                 from ../drafter/ext/snowcrash/src/SectionParserData.h:12,
                 from ../drafter/ext/snowcrash/src/SectionProcessor.h:12,
                 from ../drafter/ext/snowcrash/src/SignatureSectionProcessor.h:12,
                 from ../drafter/ext/snowcrash/src/SectionParser.h:13,
                 from ../drafter/ext/snowcrash/src/HeadersParser.h:12,
                 from ../drafter/ext/snowcrash/src/HeadersParser.cc:1:
../drafter/ext/snowcrash/src/MSONSourcemap.h:177:51: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
         std::auto_ptr<SourceMap<mson::Elements> > m_elements;
                                                   ^
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/posix/RegexMatch.o
  AR(target) Release/obj.target/drafter/ext/snowcrash/snowcrash.a
  COPY Release/snowcrash.a
  CC(target) Release/obj.target/libsundown/drafter/ext/snowcrash/ext/markdown-parser/ext/sundown/src/autolink.o
  CC(target) Release/obj.target/libsundown/drafter/ext/snowcrash/ext/markdown-parser/ext/sundown/src/buffer.o
  CC(target) Release/obj.target/libsundown/drafter/ext/snowcrash/ext/markdown-parser/ext/sundown/src/markdown.o
  CC(target) Release/obj.target/libsundown/drafter/ext/snowcrash/ext/markdown-parser/ext/sundown/src/src_map.o
  CC(target) Release/obj.target/libsundown/drafter/ext/snowcrash/ext/markdown-parser/ext/sundown/src/stack.o
  CC(target) Release/obj.target/libsundown/drafter/ext/snowcrash/ext/markdown-parser/ext/sundown/html/houdini_href_e.o
  CC(target) Release/obj.target/libsundown/drafter/ext/snowcrash/ext/markdown-parser/ext/sundown/html/houdini_html_e.o
  CC(target) Release/obj.target/libsundown/drafter/ext/snowcrash/ext/markdown-parser/ext/sundown/html/html.o
  CC(target) Release/obj.target/libsundown/drafter/ext/snowcrash/ext/markdown-parser/ext/sundown/html/html_smartypants.o
  AR(target) Release/obj.target/drafter/ext/snowcrash/sundown.a
  COPY Release/sundown.a
  CXX(target) Release/obj.target/libdrafter/drafter/src/drafter.o
In file included from ../drafter/ext/snowcrash/src/Blueprint.h:17:0,
                 from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:12,
                 from ../drafter/ext/snowcrash/src/snowcrash.h:12,
                 from ../drafter/src/drafter.h:13,
                 from ../drafter/src/drafter.cc:9:
../drafter/ext/snowcrash/src/MSON.h:371:37: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
             std::auto_ptr<Elements> m_elements;
                                     ^
In file included from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:13:0,
                 from ../drafter/ext/snowcrash/src/snowcrash.h:12,
                 from ../drafter/src/drafter.h:13,
                 from ../drafter/src/drafter.cc:9:
../drafter/ext/snowcrash/src/MSONSourcemap.h:177:51: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
         std::auto_ptr<SourceMap<mson::Elements> > m_elements;
                                                   ^
  CXX(target) Release/obj.target/libdrafter/drafter/src/cdrafter.o
In file included from ../drafter/ext/snowcrash/src/Blueprint.h:17:0,
                 from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:12,
                 from ../drafter/ext/snowcrash/src/snowcrash.h:12,
                 from ../drafter/src/cdrafter.cc:3:
../drafter/ext/snowcrash/src/MSON.h:371:37: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
             std::auto_ptr<Elements> m_elements;
                                     ^
In file included from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:13:0,
                 from ../drafter/ext/snowcrash/src/snowcrash.h:12,
                 from ../drafter/src/cdrafter.cc:3:
../drafter/ext/snowcrash/src/MSONSourcemap.h:177:51: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
         std::auto_ptr<SourceMap<mson::Elements> > m_elements;
                                                   ^
  CXX(target) Release/obj.target/libdrafter/drafter/src/Serialize.o
In file included from ../drafter/ext/snowcrash/src/Blueprint.h:17:0,
                 from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:12,
                 from ../drafter/src/Serialize.h:13,
                 from ../drafter/src/Serialize.cc:9:
../drafter/ext/snowcrash/src/MSON.h:371:37: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
             std::auto_ptr<Elements> m_elements;
                                     ^
In file included from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:13:0,
                 from ../drafter/src/Serialize.h:13,
                 from ../drafter/src/Serialize.cc:9:
../drafter/ext/snowcrash/src/MSONSourcemap.h:177:51: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
         std::auto_ptr<SourceMap<mson::Elements> > m_elements;
                                                   ^
  CXX(target) Release/obj.target/libdrafter/drafter/src/SerializeAST.o
In file included from ../drafter/ext/snowcrash/src/Blueprint.h:17:0,
                 from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:12,
                 from ../drafter/src/Serialize.h:13,
                 from ../drafter/src/SerializeAST.h:12,
                 from ../drafter/src/SerializeAST.cc:10:
../drafter/ext/snowcrash/src/MSON.h:371:37: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
             std::auto_ptr<Elements> m_elements;
                                     ^
In file included from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:13:0,
                 from ../drafter/src/Serialize.h:13,
                 from ../drafter/src/SerializeAST.h:12,
                 from ../drafter/src/SerializeAST.cc:10:
../drafter/ext/snowcrash/src/MSONSourcemap.h:177:51: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
         std::auto_ptr<SourceMap<mson::Elements> > m_elements;
                                                   ^
  CXX(target) Release/obj.target/libdrafter/drafter/src/SerializeSourcemap.o
In file included from ../drafter/ext/snowcrash/src/Blueprint.h:17:0,
                 from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:12,
                 from ../drafter/src/Serialize.h:13,
                 from ../drafter/src/SerializeSourcemap.h:12,
                 from ../drafter/src/SerializeSourcemap.cc:9:
../drafter/ext/snowcrash/src/MSON.h:371:37: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
             std::auto_ptr<Elements> m_elements;
                                     ^
In file included from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:13:0,
                 from ../drafter/src/Serialize.h:13,
                 from ../drafter/src/SerializeSourcemap.h:12,
                 from ../drafter/src/SerializeSourcemap.cc:9:
../drafter/ext/snowcrash/src/MSONSourcemap.h:177:51: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
         std::auto_ptr<SourceMap<mson::Elements> > m_elements;
                                                   ^
  CXX(target) Release/obj.target/libdrafter/drafter/src/SerializeResult.o
In file included from ../drafter/ext/snowcrash/src/Blueprint.h:17:0,
                 from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:12,
                 from ../drafter/src/Serialize.h:13,
                 from ../drafter/src/SerializeResult.h:12,
                 from ../drafter/src/SerializeResult.cc:9:
../drafter/ext/snowcrash/src/MSON.h:371:37: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
             std::auto_ptr<Elements> m_elements;
                                     ^
In file included from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:13:0,
                 from ../drafter/src/Serialize.h:13,
                 from ../drafter/src/SerializeResult.h:12,
                 from ../drafter/src/SerializeResult.cc:9:
../drafter/ext/snowcrash/src/MSONSourcemap.h:177:51: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
         std::auto_ptr<SourceMap<mson::Elements> > m_elements;
                                                   ^
  AR(target) Release/obj.target/drafter/drafter.a
  COPY Release/drafter.a
  CXX(target) Release/obj.target/libsos/drafter/ext/sos/src/sos.o
  AR(target) Release/obj.target/drafter/sos.a
  COPY Release/sos.a
  CXX(target) Release/obj.target/protagonist/src/annotation.o
In file included from ../src/protagonist.h:6:0,
                 from ../src/annotation.cc:1:
../node_modules/nan/nan.h:261:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:256:25: error: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h:661:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:661:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:665:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:665:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:672:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:672:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/protagonist.h:6,
                 from ../src/annotation.cc:1:
/home/tbostelmann/.node-gyp/4.1.1/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/tbostelmann/.node-gyp/4.1.1/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/tbostelmann/.node-gyp/4.1.1/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/tbostelmann/.node-gyp/4.1.1/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/protagonist.h:6:0,
                 from ../src/annotation.cc:1:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:676:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:683:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
In file included from ../drafter/ext/snowcrash/src/Blueprint.h:17:0,
                 from ../src/protagonist.h:7,
                 from ../src/annotation.cc:1:
../drafter/ext/snowcrash/src/MSON.h: At global scope:
../drafter/ext/snowcrash/src/MSON.h:371:37: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
             std::auto_ptr<Elements> m_elements;
                                     ^
In file included from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:13:0,
                 from ../src/protagonist.h:8,
                 from ../src/annotation.cc:1:
../drafter/ext/snowcrash/src/MSONSourcemap.h:177:51: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
         std::auto_ptr<SourceMap<mson::Elements> > m_elements;
                                                   ^
make: *** [Release/obj.target/protagonist/src/annotation.o] Error 1
make: Leaving directory `/home/tbostelmann/.nvm/versions/node/v4.1.1/lib/node_modules/apib2swagger/node_modules/protagonist/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/tbostelmann/.nvm/versions/node/v4.1.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-25-generic
gyp ERR! command "/home/tbostelmann/.nvm/versions/node/v4.1.1/bin/node" "/home/tbostelmann/.nvm/versions/node/v4.1.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/tbostelmann/.nvm/versions/node/v4.1.1/lib/node_modules/apib2swagger/node_modules/protagonist
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/home/tbostelmann/.nvm/versions/node/v4.1.1/bin/node" "/home/tbostelmann/.nvm/versions/node/v4.1.1/bin/npm" "install" "-g" "apib2swagger"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! protagonist@0.20.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the protagonist@0.20.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the protagonist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls protagonist
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tbostelmann/npm-debug.log

**Comment by kminami** [comment]
Thank you for reporting.
It is an issue of nan 1.x and protagonist.
see https://github.com/apiaryio/protagonist/issues/81
I'll update README.md to describe supported node versions.

**Comment by tbostelmann** [comment]
Ah, that's right.  Sorry for the spam.  I'll report this to the protagonist project.  Thanks.
