### ISSUE TITLE
Issue with Example Value Model output

### ISSUE THREAD

**Issue by JonBishopFox** [kminami/apib2swagger#57]
Hi @kminami,

I found something interesting and I could not figure out why the body of the form is wrapped in an array.

In my api.md 
<img width="635" alt="Screen Shot 2022-02-23 at 3 22 24 PM" src="https://user-images.githubusercontent.com/85314721/155426513-078018b0-c5b1-4232-9932-b16744f9f1b7.png">

The output in JSON
![Screen Shot 2022-02-23 at 3 22 05 PM](https://user-images.githubusercontent.com/85314721/155426531-162a2b33-f143-48c6-a611-3978b79250d5.png)

Is there a solution for this issue?

I expect the response body should be:
```
[
  "example1.com",
  "example2.com"
]
```

**Comment by kminami** [comment]
Thank you for reporting!
It's just a bug around example and fixed at v1.14.1.
Please confirm.

**Comment by kminami** [comment]
Confirmed at https://github.com/kminami/apib2swagger/pull/42#issuecomment-1058338419
